In [55]:
from pathlib import Path
import pandas as pd

In [56]:
inputfilepath = Path(r"C:\Users\jasonjia\Dropbox\Projects\conference_call\output\04_keyword_identification\04.8_entry_files_combined\sixunandjason\v5\entryfiles_combined_v5_withparagraphs_andgvkey.xlsx")

In [57]:
df = pd.read_excel(inputfilepath, sheet_name = 0)

In [58]:
df

,Keywords,Paragraph,Date,gvkey,Title,Subtitle,Report
0,interest rate,MS. LYNNE PARSHALL: We ended the first quarter...,2002-07-03,24040.0,ISIS PHARMACEUTICALS (ISIS) - ISIS PHARMACEUTI...,Â,8008277
1,interest rate,"35%, we anticipate margins in the fourth quar...",2002-07-24,65570.0,AMERICAN ITALIAN PASTA (PLB) - Q3 2002 FINANCI...,Â,8009744
2,interest rate,MR. DINNI JAIN: Sure. As of June 30th we had 1...,2002-07-24,122096.0,INSIGHT COMMUNICATIONS (ICCI) - Q2 2002 FINANC...,Â,8009801
3,discount rate,MR. GERRY LUTERMAN: This is Gerry Luterman. Le...,2002-07-25,6799.0,KEYSPAN CORP. (KSE) - Q2 2002 FINANCIAL RELEAS...,Â,8009965
4,irr,people per year. It has 300 retail stores inc...,2002-07-31,NaN,SIMON PROPERTY GROUP INCORPORATED (SPG) - Q2 2...,NaN,8710501
...,...,...,...,...,...,...,...
80637,cost of equity,We're confident Stage 3 is well positioned for...,2021-09-07,29453.0,CHENIERE ENERGY INC,LNG.A - Event Transcript of Cheniere Energy In...,72918196
80638,cost of debt,Michael Webber - Webber Research & Advisory LL...,2021-09-07,29453.0,CHENIERE ENERGY INC,LNG.A - Event Brief of Cheniere Energy Inc con...,72918224
80639,irr,"On ESG, we just discussed. On performance, oka...",2021-09-07,296577.0,APERAM SA,APAM.AS - Event Transcript of Aperam SA confer...,72931747
80640,interest rate,Looking at Global Broking revenue by asset cla...,2021-09-07,241016.0,TP ICAP GROUP PLC,TCAPI.L - Event Transcript of TP ICAP Group PL...,72939535
80641,roic,Moving on to Slide #3 now and speaking about -...,2021-08-12,345256.0,AERIS INDUSTRIA E COMERCIO DE EQUIPAMENTOS PAR...,AERI3.SA - Event Transcript of Aeris Industria...,72975318

In [59]:
df_report = df['Report']

In [60]:
df_report.unique()

array([ 8008277,  8009744,  8009801, ..., 72931747, 72939535, 72975318],
      dtype=int64)

In [61]:
df_report.unique().shape

(69381,)

In [62]:
df_report.nunique(dropna = True)

69381

In [63]:
df_report = pd.DataFrame(df_report.unique())

In [64]:
df_report

              0
0       8008277
1       8009744
2       8009801
3       8009965
4       8710501
...         ...
69376  72918196
69377  72918224
69378  72931747
69379  72939535
69380  72975318

[69381 rows x 1 columns]

In [65]:
df_report.to_csv(r"C:\Users\jasonjia\Dropbox\Projects\conference_call\output\12_summary_statistics\unique_conference_calls_with_keywords.csv", header=None, index=False)

In [66]:
# Filter to get unique Report IDs, but save all the columns instead
first = df.groupby('Report').first().reset_index()
first

,Report,Keywords,Paragraph,Date,gvkey,Title,Subtitle
0,8008277,interest rate,MS. LYNNE PARSHALL: We ended the first quarter...,2002-07-03,24040.0,ISIS PHARMACEUTICALS (ISIS) - ISIS PHARMACEUTI...,Â
1,8009744,interest rate,"35%, we anticipate margins in the fourth quar...",2002-07-24,65570.0,AMERICAN ITALIAN PASTA (PLB) - Q3 2002 FINANCI...,Â
2,8009801,interest rate,MR. DINNI JAIN: Sure. As of June 30th we had 1...,2002-07-24,122096.0,INSIGHT COMMUNICATIONS (ICCI) - Q2 2002 FINANC...,Â
3,8009965,discount rate,MR. GERRY LUTERMAN: This is Gerry Luterman. Le...,2002-07-25,6799.0,KEYSPAN CORP. (KSE) - Q2 2002 FINANCIAL RELEAS...,Â
4,8710501,irr,people per year. It has 300 retail stores inc...,2002-07-31,NaN,SIMON PROPERTY GROUP INCORPORATED (SPG) - Q2 2...,None
...,...,...,...,...,...,...,...
69376,72918196,cost of equity,We're confident Stage 3 is well positioned for...,2021-09-07,29453.0,CHENIERE ENERGY INC,LNG.A - Event Transcript of Cheniere Energy In...
69377,72918224,cost of debt,Michael Webber - Webber Research & Advisory LL...,2021-09-07,29453.0,CHENIERE ENERGY INC,LNG.A - Event Brief of Cheniere Energy Inc con...
69378,72931747,irr,"On ESG, we just discussed. On performance, oka...",2021-09-07,296577.0,APERAM SA,APAM.AS - Event Transcript of Aperam SA confer...
69379,72939535,interest rate,Looking at Global Broking revenue by asset cla...,2021-09-07,241016.0,TP ICAP GROUP PLC,TCAPI.L - Event Transcript of TP ICAP Group PL...
69380,72975318,roic,Moving on to Slide #3 now and speaking about -...,2021-08-12,345256.0,AERIS INDUSTRIA E COMERCIO DE EQUIPAMENTOS PAR...,AERI3.SA - Event Transcript of Aeris Industria...

In [68]:
first.to_csv(r"C:\Users\jasonjia\Dropbox\Projects\conference_call\output\12_summary_statistics\unique_conference_calls_with_keywords_all_columns.csv", index=False)