In [169]:
from pathlib import Path
import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 30)

# Part 1: Combine xls_compiled from the 2 pulls

In [170]:
xls_compiled_1_path = Path(r"C:\Users\jasonjia\Dropbox\Projects\conference_call\output\12_summary_statistics\xls_compiled_01.1_xls_1.csv")
xls_compiled_2_path = Path(r"C:\Users\jasonjia\Dropbox\Projects\conference_call\output\12_summary_statistics\xls_compiled_01.1_xls_2.csv")
xls_compiled_path = Path(r"C:\Users\jasonjia\Dropbox\Projects\conference_call\output\12_summary_statistics\xls_compiled_01.1_xls_1_and_2.csv")

In [ ]:
xls_compiled_1 = pd.read_csv(xls_compiled_1_path, low_memory=False)
xls_compiled_2 = pd.read_csv(xls_compiled_2_path, low_memory=False)

# "Stack" the two DataFrames together
xls_compiled = pd.concat([xls_compiled_1, xls_compiled_2], ignore_index=True)

# Save df to new csv file
xls_compiled.to_csv(xls_compiled_path, index=False)

In [43]:
# Delete the dfs to clear memory
del xls_compiled_1
del xls_compiled_2
del xls_compiled

# Part 2: Get the firm names of conference calls with matches

In [193]:
xls_compiled_path = Path(r"C:\Users\jasonjia\Dropbox\Projects\conference_call\output\12_summary_statistics\xls_compiled_01.1_xls_1_and_2.csv")
unique_conference_calls_with_keywords_path = Path(r"C:\Users\jasonjia\Dropbox\Projects\conference_call\output\12_summary_statistics\unique_conference_calls_with_keywords_all_columns.csv")

In [194]:
xls_compiled = pd.read_csv(xls_compiled_path, low_memory=False)
xls_compiled = xls_compiled[['Report #', 'Title', 'Subtitle']]
xls_compiled = xls_compiled.dropna(subset=['Report #'])
xls_compiled = xls_compiled.astype({'Report #': 'int64'})
xls_compiled

,Report #,Title,Subtitle
0,21044925,FUEL SYSTEMS SOLUTIONS INC,FSYS.OQ - Event Transcript of Fuel Systems Sol...
1,21045694,NN INC,NNBR.OQ - Event Transcript of NN Inc conferenc...
2,21045712,COPANO ENERGY LLC,CPNO.OQ - Event Transcript of Copano Energy LL...
3,21045002,SODEXO,EXHO.PA - Event Transcript of Sodexo SA confer...
4,21045791,VULCAN MATERIALS CO.,VMC.N - Event Transcript of Vulcan Materials C...
...,...,...,...
588235,72918201,FINGERPRINT CARDS AB,FINGb.ST - Event Transcript of Fingerprint Car...
588236,72912303,HANSEN TECHNOLOGIES LIMITED,HSN.AX - Event Transcript of Hansen Technologi...
588237,72905849,ACCESS BANK NIGERIA PLC,ACCESS.LG - Event Transcript of Access Bank Pl...
588238,72905854,AFRICAN RAINBOW MINERALS LTD,ARIJ.J - Event Transcript of African Rainbow M...
588239,72905855,INTEGRATED DIAGNOSTICS HOLDINGS PLC,IDHC.L - Event Transcript of Integrated Diagno...

In [195]:
unique_conference_calls_with_keywords = pd.read_csv(unique_conference_calls_with_keywords_path)
unique_conference_calls_with_keywords = unique_conference_calls_with_keywords[['Report', 'gvkey', 'Title']]
unique_conference_calls_with_keywords = unique_conference_calls_with_keywords.rename(columns = {'Report': 'Report #', 'Title': "Title_v2"})
unique_conference_calls_with_keywords

       Report #     gvkey                                           Title_v2
0       8008277   24040.0  ISIS PHARMACEUTICALS (ISIS) - ISIS PHARMACEUTI...
1       8009744   65570.0  AMERICAN ITALIAN PASTA (PLB) - Q3 2002 FINANCI...
2       8009801  122096.0  INSIGHT COMMUNICATIONS (ICCI) - Q2 2002 FINANC...
3       8009965    6799.0  KEYSPAN CORP. (KSE) - Q2 2002 FINANCIAL RELEAS...
4       8710501       NaN  SIMON PROPERTY GROUP INCORPORATED (SPG) - Q2 2...
...         ...       ...                                                ...
69376  72918196   29453.0                                CHENIERE ENERGY INC
69377  72918224   29453.0                                CHENIERE ENERGY INC
69378  72931747  296577.0                                          APERAM SA
69379  72939535  241016.0                                  TP ICAP GROUP PLC
69380  72975318  345256.0  AERIS INDUSTRIA E COMERCIO DE EQUIPAMENTOS PAR...

[69381 rows x 3 columns]

In [196]:
# Merge
final = unique_conference_calls_with_keywords.merge(xls_compiled, how='left', on = "Report #")
final

,Report #,gvkey,Title_v2,Title,Subtitle
0,8008277,24040.0,ISIS PHARMACEUTICALS (ISIS) - ISIS PHARMACEUTI...,ISIS PHARMACEUTICALS (ISIS) - ISIS PHARMACEUTI...,NaN
1,8009744,65570.0,AMERICAN ITALIAN PASTA (PLB) - Q3 2002 FINANCI...,AMERICAN ITALIAN PASTA (PLB) - Q3 2002 FINANCI...,NaN
2,8009801,122096.0,INSIGHT COMMUNICATIONS (ICCI) - Q2 2002 FINANC...,INSIGHT COMMUNICATIONS (ICCI) - Q2 2002 FINANC...,NaN
3,8009965,6799.0,KEYSPAN CORP. (KSE) - Q2 2002 FINANCIAL RELEAS...,KEYSPAN CORP. (KSE) - Q2 2002 FINANCIAL RELEAS...,NaN
4,8710501,NaN,SIMON PROPERTY GROUP INCORPORATED (SPG) - Q2 2...,SIMON PROPERTY GROUP INCORPORATED (SPG) - Q2 2...,NaN
...,...,...,...,...,...
73165,72918196,29453.0,CHENIERE ENERGY INC,CHENIERE ENERGY INC,LNG.A - Event Transcript of Cheniere Energy In...
73166,72918224,29453.0,CHENIERE ENERGY INC,CHENIERE ENERGY INC,LNG.A - Event Brief of Cheniere Energy Inc con...
73167,72931747,296577.0,APERAM SA,APERAM SA,APAM.AS - Event Transcript of Aperam SA confer...
73168,72939535,241016.0,TP ICAP GROUP PLC,TP ICAP GROUP PLC,TCAPI.L - Event Transcript of TP ICAP Group PL...
73169,72975318,345256.0,AERIS INDUSTRIA E COMERCIO DE EQUIPAMENTOS PAR...,AERIS INDUSTRIA E COMERCIO DE EQUIPAMENTOS PAR...,AERI3.SA - Event Transcript of Aeris Industria...

In [197]:
# Check if there are any non-matches - none. Good!
final[final['Title'].isna()]

Empty DataFrame
Columns: [Report #, gvkey, Title_v2, Title, Subtitle]
Index: []

In [198]:
# Identify duplicate report #s
duplicateRows = final[final.duplicated(['Report #'])]
duplicateRows

,Report #,gvkey,Title_v2,Title,Subtitle
10,8720951,29511.0,"CYTEC INDUSTRIES, INC. (CYT) - Q4 2002 FINANCI...","CYTEC INDUSTRIES, INC. (CYT) - Q4 2002 FINANCI...",NaN
12,8720956,61679.0,GREATER BAY BANCORP (GBBK) - Q4 2002 FINANCIAL...,GREATER BAY BANCORP (GBBK) - Q4 2002 FINANCIAL...,NaN
15,8721123,65156.0,CHOICE POINT INC (CPS) - Q4 2002 FINANCIAL REL...,CHOICE POINT INC (CPS) - Q4 2002 FINANCIAL REL...,NaN
194,8902240,61388.0,"EVEREST RE GROUP, LTD. (RE) - Q2 2003 FINANCIA...","EVEREST RE GROUP, LTD. (RE) - Q2 2003 FINANCIA...",NaN
196,8902250,61388.0,"EVEREST RE GROUP, LTD. (RE) - Q2 2003 FINANCIA...","EVEREST RE GROUP, LTD. (RE) - Q2 2003 FINANCIA...",NaN
...,...,...,...,...,...
72847,72743526,184689.0,GOLUB CAPITAL BDC INC,GOLUB CAPITAL BDC INC,GBDC.OQ - Event Transcript of Golub Capital BD...
73094,72838906,226744.0,RAMSAY HEALTH CARE LTD,RAMSAY HEALTH CARE LTD,RHC.AX - Event Transcript of Ramsay Health Car...
73097,72838910,179107.0,CHAMPION IRON LTD,CHAMPION IRON LTD,CIA.TO - Event Transcript of Champion Iron Ltd...
73101,72838926,157855.0,SALESFORCE COM INC,SALESFORCE COM INC,CRM.N - Event Transcript of Salesforce.Com Inc...
73112,72839062,157855.0,SALESFORCE COM INC,SALESFORCE COM INC,CRM.N - Event Brief of Salesforce.Com Inc conf...

In [199]:
# Do a few checks - confirm that the titles are the same.
final[final['Report #'] == 8720951]

,Report #,gvkey,Title_v2,Title,Subtitle
9,8720951,29511.0,"CYTEC INDUSTRIES, INC. (CYT) - Q4 2002 FINANCI...","CYTEC INDUSTRIES, INC. (CYT) - Q4 2002 FINANCI...",NaN
10,8720951,29511.0,"CYTEC INDUSTRIES, INC. (CYT) - Q4 2002 FINANCI...","CYTEC INDUSTRIES, INC. (CYT) - Q4 2002 FINANCI...",NaN

In [200]:
# Remove duplicated report #s - should have no impact.
first = final.groupby('Report #').first().reset_index()
first

,Report #,gvkey,Title_v2,Title,Subtitle
0,8008277,24040.0,ISIS PHARMACEUTICALS (ISIS) - ISIS PHARMACEUTI...,ISIS PHARMACEUTICALS (ISIS) - ISIS PHARMACEUTI...,None
1,8009744,65570.0,AMERICAN ITALIAN PASTA (PLB) - Q3 2002 FINANCI...,AMERICAN ITALIAN PASTA (PLB) - Q3 2002 FINANCI...,None
2,8009801,122096.0,INSIGHT COMMUNICATIONS (ICCI) - Q2 2002 FINANC...,INSIGHT COMMUNICATIONS (ICCI) - Q2 2002 FINANC...,None
3,8009965,6799.0,KEYSPAN CORP. (KSE) - Q2 2002 FINANCIAL RELEAS...,KEYSPAN CORP. (KSE) - Q2 2002 FINANCIAL RELEAS...,None
4,8710501,NaN,SIMON PROPERTY GROUP INCORPORATED (SPG) - Q2 2...,SIMON PROPERTY GROUP INCORPORATED (SPG) - Q2 2...,None
...,...,...,...,...,...
69376,72918196,29453.0,CHENIERE ENERGY INC,CHENIERE ENERGY INC,LNG.A - Event Transcript of Cheniere Energy In...
69377,72918224,29453.0,CHENIERE ENERGY INC,CHENIERE ENERGY INC,LNG.A - Event Brief of Cheniere Energy Inc con...
69378,72931747,296577.0,APERAM SA,APERAM SA,APAM.AS - Event Transcript of Aperam SA confer...
69379,72939535,241016.0,TP ICAP GROUP PLC,TP ICAP GROUP PLC,TCAPI.L - Event Transcript of TP ICAP Group PL...
69380,72975318,345256.0,AERIS INDUSTRIA E COMERCIO DE EQUIPAMENTOS PAR...,AERIS INDUSTRIA E COMERCIO DE EQUIPAMENTOS PAR...,AERI3.SA - Event Transcript of Aeris Industria...

In [201]:
# Check # of NaNs in Title_v2 - confirm that there's 0
first.groupby('Title_v2').first().reset_index()['Title_v2'].isna().sum()

0

In [202]:
# Filter by Title_v2 since there's no NaNs in Title_v2, whereas there are NaNs in Title
second = first.groupby('Title_v2').first().reset_index()
second

,Title_v2,Report #,gvkey,Title,Subtitle
0,**CCBN - EVENT BRIEF OF CCBN.COM CONFERENCE CA...,21466001,NaN,**CCBN - EVENT BRIEF OF CCBN.COM CONFERENCE CA...,**ccbn - Event Brief of CCBN.com conference ca...
1,**CGL - EVENT TRANSCRIPT OF CHRYSLER GROUP LLC...,18726507,NaN,**CGL - EVENT TRANSCRIPT OF CHRYSLER GROUP LLC...,**CGL - Event Transcript of Chrysler Group LLC...
2,**CGL - EVENT TRANSCRIPT OF CHRYSLER GROUP LLC...,21380912,NaN,**CGL - EVENT TRANSCRIPT OF CHRYSLER GROUP LLC...,**CGL - Event Transcript of Chrysler Group LLC...
3,**ECB - EVENT TRANSCRIPT OF EUROPEAN CENTRAL B...,20332970,328976.0,**ECB - EVENT TRANSCRIPT OF EUROPEAN CENTRAL B...,**ECB - Event Transcript of European Central B...
4,**LEVI - EVENT TRANSCRIPT OF LEVI STRAUSS & CO...,62404807,16476.0,**LEVI - EVENT TRANSCRIPT OF LEVI STRAUSS & CO...,**LEVI - Event Transcript of Levi Strauss & Co...
...,...,...,...,...,...
14382,ZURICH FINANCIAL SERVICES AG,10551933,313992.0,ZURICH FINANCIAL SERVICES AG,"ZFSVY conference call Final transcript, 18-Aug..."
14383,ZURICH FINANCIAL SERVICES AG - FINAL TRANSCRIPT,14730144,313992.0,ZURICH FINANCIAL SERVICES AG - FINAL TRANSCRIPT,"ZFSVF.PK conference call Final transcript, 5-N..."
14384,ZURICH FINANCIAL SERVICES AG - PRELIMINARY TRA...,15164317,313992.0,ZURICH FINANCIAL SERVICES AG - PRELIMINARY TRA...,None
14385,ZURICH INSURANCE GROUP AG,20203521,220426.0,ZURICH INSURANCE GROUP AG,ZURN.VX - Event Transcript of Zurich Insurance...
14386,ZURICH PROTECTOR FORSIKRING AS,63252524,222004.0,ZURICH PROTECTOR FORSIKRING AS,PROTCT.OL - Event Transcript of Protector Fors...

In [203]:
# There are clearly differences in the titles. I trust title_v2 more, since it's been manually looked at.
second[second['Title_v2'] != second ['Title']]

,Title_v2,Report #,gvkey,Title,Subtitle
115,- EVENT TRANSCRIPT OF NORWEGIAN FINANS HOLDING...,72766281,317887.0,#NAME?,- Event Transcript of Norwegian Finans Holding...
135,- EVENT TRANSCRIPT OF ROTOPLAS SA DE CV CONFER...,71926037,291185.0,#NAME?,- Event Transcript of Rotoplas SA de CV confer...
256,ABERTIS INFRAESTRUCTURAS SA,11471979,102629.0,ABERTIS INFRAESTRUCTURAS SA,ABRTY.PK - Event Transcript of Abertis confere...
257,ABERTIS INFRAESTRUCTURAS SA - FINAL TRANSCRIPT,12558930,102629.0,ABERTIS INFRAESTRUCTURAS SA - FINAL TRANSCRIPT,"ABFZF.OTC conference call Final transcript, 8-..."
258,ABERTIS INFRAESTRUCTURAS SA - PRELIMINARY TRA...,13197773,102629.0,ABERTIS INFRAESTRUCTURAS SA - PRELIMINARY TRAN...,"ABFZF.PK conference call Final transcript, 28-..."
...,...,...,...,...,...
13416,UNITED COMMUNITY BANKS INC,9904717,64794.0,UNITED COMMUNITY BANKS INC,"UCBI conference call Final transcript, 23-Jan-..."
13417,UNITED COMMUNITY BANKS INC - FINAL TRANSCRIPT,12453015,64794.0,UNITED COMMUNITY BANKS INC - FINAL TRANSCRIPT,"UCBI conference call Final transcript, 24-Jul-..."
13418,UNITED COMMUNITY BANKS INC - PRELIMINARY TRAN...,16413468,64794.0,UNITED COMMUNITY BANKS INC - PRELIMINARY TRANS...,None
13648,VEREIT INC,22367640,186783.0,AMERICAN REALTY CAPITAL PROPERTIES INC,ARCP.OQ - Event Transcript of American Realty ...
13722,VIRGIN MEDIA INC - PRELIMINARY TRANSCRIPT,13196051,153668.0,VIRGIN MEDIA INC - PRELIMINARY TRANSCRIPT,VIRGIN MEDIA INC - PRELIMINARY TRANSCRIPT

In [204]:
df = second

In [205]:
second['Title'][57]

'- EVENT TRANSCRIPT OF ASSOCIATED ESTATES REALTY CORP CONFERENC'

In [206]:
# Replace a with b for all strings in a df column at all occurences
df['Title_v2_truncated'] = df['Title_v2'].str.replace(r'^.*- event .+ of ','', regex = True, case=False)
df['Title_v2_truncated'] = df['Title_v2_truncated'].str.replace(r'conference call.*','', regex = True, case=False)
df['Title_v2_truncated'] = df['Title_v2_truncated'].str.replace(r' -.+ transcript.*$','', regex = True, case=False)
df['Title_v2_truncated'] = df['Title_v2_truncated'].str.replace(r' - preliminary .*$','', regex = True, case=False)
df['Title_v2_truncated'] = df['Title_v2_truncated'].str.replace(r' confere.*$','', regex = True, case=False)
df['Title_v2_truncated'] = df['Title_v2_truncated'].str.replace(r' - Q\d \d\d\d\d .*$','', regex = True, case=False)

In [207]:
df

,Title_v2,Report #,gvkey,Title,Subtitle,Title_v2_truncated
0,**CCBN - EVENT BRIEF OF CCBN.COM CONFERENCE CA...,21466001,NaN,**CCBN - EVENT BRIEF OF CCBN.COM CONFERENCE CA...,**ccbn - Event Brief of CCBN.com conference ca...,CCBN.COM
1,**CGL - EVENT TRANSCRIPT OF CHRYSLER GROUP LLC...,18726507,NaN,**CGL - EVENT TRANSCRIPT OF CHRYSLER GROUP LLC...,**CGL - Event Transcript of Chrysler Group LLC...,CHRYSLER GROUP LLC
2,**CGL - EVENT TRANSCRIPT OF CHRYSLER GROUP LLC...,21380912,NaN,**CGL - EVENT TRANSCRIPT OF CHRYSLER GROUP LLC...,**CGL - Event Transcript of Chrysler Group LLC...,CHRYSLER GROUP LLC
3,**ECB - EVENT TRANSCRIPT OF EUROPEAN CENTRAL B...,20332970,328976.0,**ECB - EVENT TRANSCRIPT OF EUROPEAN CENTRAL B...,**ECB - Event Transcript of European Central B...,EUROPEAN CENTRAL BANK
4,**LEVI - EVENT TRANSCRIPT OF LEVI STRAUSS & CO...,62404807,16476.0,**LEVI - EVENT TRANSCRIPT OF LEVI STRAUSS & CO...,**LEVI - Event Transcript of Levi Strauss & Co...,LEVI STRAUSS & CO
...,...,...,...,...,...,...
14382,ZURICH FINANCIAL SERVICES AG,10551933,313992.0,ZURICH FINANCIAL SERVICES AG,"ZFSVY conference call Final transcript, 18-Aug...",ZURICH FINANCIAL SERVICES AG
14383,ZURICH FINANCIAL SERVICES AG - FINAL TRANSCRIPT,14730144,313992.0,ZURICH FINANCIAL SERVICES AG - FINAL TRANSCRIPT,"ZFSVF.PK conference call Final transcript, 5-N...",ZURICH FINANCIAL SERVICES AG
14384,ZURICH FINANCIAL SERVICES AG - PRELIMINARY TRA...,15164317,313992.0,ZURICH FINANCIAL SERVICES AG - PRELIMINARY TRA...,None,ZURICH FINANCIAL SERVICES AG
14385,ZURICH INSURANCE GROUP AG,20203521,220426.0,ZURICH INSURANCE GROUP AG,ZURN.VX - Event Transcript of Zurich Insurance...,ZURICH INSURANCE GROUP AG
14386,ZURICH PROTECTOR FORSIKRING AS,63252524,222004.0,ZURICH PROTECTOR FORSIKRING AS,PROTCT.OL - Event Transcript of Protector Fors...,ZURICH PROTECTOR FORSIKRING AS

In [209]:
df.to_excel(r"C:\Users\jasonjia\Dropbox\Projects\conference_call\output\12_summary_statistics\unique_conference_calls_with_keywords_truncated_titles_to_check_for_correct_firm_name.xlsx", index=False)